services:
  recorder:
    build:
      context: .
      dockerfile: docker/Dockerfile.recorder
    volumes:
      - ./storage/recordings:/recordings
      - radio_logs:/var/log/radio
      - ./config:/config:ro
    environment:
      - TZ=America/Denver
    user: "8000:8000"
    restart: unless-stopped

  broadcaster:
    build:
      context: .
      dockerfile: docker/Dockerfile.broadcaster
    volumes:
      - ./storage/recordings:/recordings:ro
      - ./storage/sorted_recordings:/sorted_recordings:rw
      - ./storage/logs/radio-service:/var/log/radio-service:rw
      - ./config:/config:ro
      - ./config/icecast.xml:/etc/icecast2/icecast.xml:ro
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Denver
    depends_on:
      - recorder
    restart: unless-stopped

volumes:
  recordings:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_PWD:-${PWD:-$(pwd)}}/storage/recordings
  radio_logs:
    driver: local
